// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCoAuP-g6ZA_h33CbAmhTfkT_1O3vavL7U',
//     appId: '1:112881078058:web:248e4de58e0b40d382d853',
//     messagingSenderId: '112881078058',
//     projectId: 'proj001-6f766',
//     authDomain: 'proj001-6f766.firebaseapp.com',
//     databaseURL: 'https://proj001-6f766-default-rtdb.firebaseio.com',
//     storageBucket: 'proj001-6f766.appspot.com',
//     measurementId: 'G-MGZ7NX7041',
//   );

//   // static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCN6bHWdb0Wix6M2zA4AVXqvWEyehF0Was',
//     appId: '1:112881078058:android:4c3ae182799fe91182d853',
//     messagingSenderId: '112881078058',
//     projectId: 'proj001-6f766',
//     databaseURL: 'https://proj001-6f766-default-rtdb.firebaseio.com',
//     storageBucket: 'proj001-6f766.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDyCHtq7ReMX7OSG2Q-iame8F2UFXmWBAs',
//     appId: '1:112881078058:ios:0f846366bcaf038682d853',
//     messagingSenderId: '112881078058',
//     projectId: 'proj001-6f766',
//     databaseURL: 'https://proj001-6f766-default-rtdb.firebaseio.com',
//     storageBucket: 'proj001-6f766.appspot.com',
//     androidClientId: '112881078058-0egv7uj1tpth5rto3lihrsaceuc4sd5v.apps.googleusercontent.com',
//     iosClientId: '112881078058-v35lng7argo37isdlkqqbchr171a6bgu.apps.googleusercontent.com',
//     iosBundleId: 'com.example.flutterfire',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDyCHtq7ReMX7OSG2Q-iame8F2UFXmWBAs',
//     appId: '1:112881078058:ios:0f846366bcaf038682d853',
//     messagingSenderId: '112881078058',
//     projectId: 'proj001-6f766',
//     databaseURL: 'https://proj001-6f766-default-rtdb.firebaseio.com',
//     storageBucket: 'proj001-6f766.appspot.com',
//     androidClientId: '112881078058-0egv7uj1tpth5rto3lihrsaceuc4sd5v.apps.googleusercontent.com',
//     iosClientId: '112881078058-v35lng7argo37isdlkqqbchr171a6bgu.apps.googleusercontent.com',
//     iosBundleId: 'com.example.flutterfire',
//   );
// }
